### ISSUE TITLE
Cadata support on python2.7

### ISSUE THREAD

**Issue by jrabbit** [jrabbit/taskd-client-py#8]
``` python
Traceback (most recent call last):
  File "simple.py", line 123, in <module>
    taskd.connect()
  File "simple.py", line 38, in connect
    c.load_verify_locations(cadata=self.cacert)
ssl.SSLError: nested asn1 error (_ssl.c:2626)
```

**Comment by jrabbit** [comment]
So this is a bug in the python docs. We need to pass a unicode object here?
https://bugs.python.org/issue29236

**Comment by jrabbit** [comment]
voiding py2 support
